# Rustfmt config to match project import style (nightly options enabled)
edition = "2021"
use_small_heuristics = "Off"
imports_granularity = "Item"
group_imports = "StdExternalCrate"
reorder_imports = false
normalize_doc_attributes = false
