# Rustfmt config to match project import style (nightly options enabled)
edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_doc_attributes = false
reorder_imports = true
use_small_heuristics = "Off"
